### ISSUE TITLE
You cannot eat honey sweetrolls

### ISSUE THREAD

**Issue by xPokee** [Bubberstation/Bubberstation#2257] opened 2024-10-23 13:02 UTC
### Client Version:

515.1640

### Issue Summary:

If you try to eat a honey sweetroll literally nothing happens. You can click yourself as much as you want but you'll never get the progress bar to eat it. This ONLY seems to be effecting honey sweetrolls.

### Round ID:

5785

### Test Merge Information:

- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [Storyteller 2.2](https://github.com/Bubberstation/Bubberstation/pull/2116)
- [Space MP5 - Redux](https://github.com/Bubberstation/Bubberstation/pull/2199)
- [Xenomorph Hybrid Rework](https://github.com/Bubberstation/Bubberstation/pull/2198)
- [Succumbing now alerts everyone around you that you gave up on life.](https://github.com/Bubberstation/Bubberstation/pull/2193)
- [Patches a bug with adding vetted users.](https://github.com/Bubberstation/Bubberstation/pull/2200)
- [Investigate Stat Panel as a Stutter cause](https://github.com/Bubberstation/Bubberstation/pull/2201)
- [Limbgrown bodies.](https://github.com/Bubberstation/Bubberstation/pull/1842)
- [(Port) MKUltra - Mind Control](https://github.com/Bubberstation/Bubberstation/pull/2206)
- [halloween: a 2spooky update](https://github.com/Bubberstation/Bubberstation/pull/2211)
- [Adds *yip and *yipyip](https://github.com/Bubberstation/Bubberstation/pull/2254)
- [Fix job title in head arrival radio messages being empty](https://github.com/Bubberstation/Bubberstation/pull/2255)

### Reproduction Steps:

1. Cook up a honey sweetroll.
2. Try to eat said sweetroll.
3. Watch as nothing happens and your spaceman inexplicitly cannot open their mouth to eat the delicious sweetroll.

**Comment by TealSeer** [comment] 2024-11-12 17:32
Couldn't reproduce this, could it be fixed now?

**Comment by Majkl-J** [comment] 2024-11-12 17:35
> Couldn't reproduce this, could it be fixed now?

If you spawn them in they work fine, you need to go through the entire recipe chain

**Comment by Majkl-J** [comment] 2024-12-18 10:41
Gonna be closing this as this is fundamentally a duplicate of #1310 as they have the same cause

**Closed by Majkl-J** 2024-12-18 10:41 UTC
Labels: CODECON 3
