### ISSUE TITLE
TGUI Broken On Clothing Recolor

### ISSUE THREAD

**Issue by Vynzill** [Bubberstation/Bubberstation#407] opened 2023-07-31 23:51 UTC
## Round ID:
1855

## Testmerges:
[#208: 'Test revert of #190 to try and solve the error-people.' by KathrinBailey at commit 9d786b9510](https://github.com/Bubberstation/Bubberstation/pull/208)
[#294: 'Blacksmithing workshops' by Scuhf-git at commit 5ec8cdaf73](https://github.com/Bubberstation/Bubberstation/pull/294)
[#248: 'Reset the Gateway to TGstation, allowing cyborgs to enter' by nevimer at commit e499e44135](https://github.com/Bubberstation/Bubberstation/pull/248)
[#241: '[MODULAR] Progtot goals override' by nevimer at commit a234c045e1](https://github.com/Bubberstation/Bubberstation/pull/241)
[#314: '[Modular] Makes all techwebs generate points' by ReturnToZender at commit 8a41be5ab2](https://github.com/Bubberstation/Bubberstation/pull/314)
[#367: 'Revert antag removal v2' by nevimer at commit 4a0dc791aa](https://github.com/Bubberstation/Bubberstation/pull/367)
[#369: 'Revert the Lizard Screams' by nevimer at commit 16ce74920b](https://github.com/Bubberstation/Bubberstation/pull/369)
[#371: 'Post-upstream fix for PR 344' by DerFlammenwerfer at commit b7ba34e9a0](https://github.com/Bubberstation/Bubberstation/pull/371)
[#306: 'Ports GAS' by nevimer at commit 93482a5952](https://github.com/Bubberstation/Bubberstation/pull/306)
[#382: 'fixes oversized synths/species with nohunger getting huge guts' by Kraseo at commit 1ec9089104](https://github.com/Bubberstation/Bubberstation/pull/382)

## Reproduction:
Attempt to recolor any clothing related item, in game or in the character loadout menu. You will get a tgui bluescreen error. Check the [screencap](https://i.imgur.com/MpW7DvW.png) for details. Has lasted multiple rounds, and I asked around and is affecting not just me.

**Comment by Majkl-J** [comment] 2023-11-28 06:44
Unable to reproduce, probably fixed by upstream

**Closed by Majkl-J** 2023-11-28 06:44 UTC
