### ISSUE TITLE
(CODE BOUNTY) - Vore 

### ISSUE THREAD

**Issue by miniusAreas** [Bubberstation/Bubberstation#464] opened 2023-08-16 17:13 UTC
Because Zender decided THIS was the correct course of action and place to put a bounty.

There is a currently a 550$ USD (80$ confirmed on my end) bounty pot for the port of Vore from VIRGO (or if you want to REALLY take your hand at it, make your own vore system.) Payment will be released upon merge and or completion of the code. Maintaining the code is not required however would be appreciated.

myself 80$
Snaffle 100$
Borger 30$
Farren (bellybird) 50$
Liujunior 15$
= 275
x2 on the Server's Bounty Pot for a total of 550$ USD. This has become the largest code bounty and or commission to date in SS13 history possibly.

**IF YOU WOULD LIKE TO ADD TO THE BOUNTY POT** please DM me on discord @miniusAreas

Shadow is currently working on this bounty! Stay tuned for updates.

**Comment by Cyprex** [comment] 2023-08-20 12:22
You need to specify what exactly you're paying how much for "uhhh port it from virgo or make your own" isn't a good prompt.

**Comment by Cyprex** [comment] 2023-08-20 12:22
Also, as I understand chomp has the best vore system?

**Comment by snaffle15** [comment] 2023-09-26 18:28
The bounty has been raised to $490.

**Comment by ploppydroppy** [comment] 2023-09-29 21:46
shut up bruh

**Comment by miniusAreas** [comment] 2023-10-03 21:19
> shut up bruh

Please keep the comments civil and for actual offers and other things. Thank you.

@ReturnToZender mods, twist his nuts.

**Comment by snaffle15** [comment] 2023-10-25 22:46
I'll front the remaining amounts to even the bounty back at $450.

**Comment by Cyprex** [comment] 2023-10-29 21:26
If you're interested in taking this please ask first, there's various things we'd like to talk about related to it, and we'd hate to have someone jump onto a bounty that's already being worked on by someone else!

**Comment by Cyprex** [comment] 2023-10-30 20:50
This is being worked on already now.

**Comment by ReturnToZender** [comment] 2023-12-13 20:07
Details being moved to #845 so that they can be maintained, @Cyprex @snaffle15

**Comment by Majkl-J** [comment] 2024-02-26 19:13
Duplicate of https://github.com/Bubberstation/Bubberstation/issues/845

**Closed by Majkl-J** 2024-02-26 19:13 UTC
Labels: Bounty
